bloggame/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('posts/', include('posts.urls')),
    path('admin/', admin.site.urls),
]

posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.list_posts, name='index'),
    path('create/', views.create_post, name='create'),
    path('<int:post_id>/', views.detail_post, name='detail'),
    path('update/<int:post_id>/', views.update_post, name='update'),
    path('delete/<int:post_id>/', views.delete_post, name='delete'),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('about/', views.about, name='about'),
    path('', views.index, name='index'),
]

posts/models.py
from django.db import models
from django.conf import settings


class Post(models.Model):
    titulo = models.CharField(max_length=255)
    data_criacao = models.DateTimeField(auto_now_add = True)
    imagem_url = models.URLField(max_length=200, null=True)
    conteudo = models.CharField(max_length=5000)

    def __str__(self):
        return f'{self.titulo} ({self.data_criacao})'

staticpages/models.py
from django.db import models

# Create your models here.

posts/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from .models import Post
from django.shortcuts import render, get_object_or_404

def list_posts(request):
    post_list = Post.objects.all()
    context = {'post_list': post_list}
    return render(request, 'posts/index.html', context)

def detail_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    context = {'post': post}
    return render(request, 'posts/detail.html', context)

def create_post(request):
    if request.method == 'POST':
        post_titulo = request.POST['titulo']
        post_imagem_url = request.POST['imagem_url']
        post_conteudo = request.POST['conteudo']
        post = Post(titulo=post_titulo,
                      imagem_url=post_imagem_url,
                      conteudo = post_conteudo)
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', args=(post.id, )))
    else:
        return render(request, 'posts/create.html', {})

def update_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.titulo = request.POST['titulo']
        post.imagem_url = request.POST['imagem_url']
        post.save()
        return HttpResponseRedirect(
            reverse('posts:detail', args=(post.id, )))

    context = {'post': post}
    return render(request, 'posts/update.html', context)


def delete_post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)

    if request.method == "POST":
        post.delete()
        return HttpResponseRedirect(reverse('posts:index'))

    context = {'post': post}
    return render(request, 'posts/delete.html', context)

staticpages/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse


def index(request):
    context = {}
    return render(request, 'staticpages/index.html', context)


def about(request):
    context = {}
    return render(request, 'staticpages/about.html', context)

posts/templates/posts/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Jogo</h2>
<form method="POST" action="{% url 'posts:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_titulo">Título:</label>
        <input type="text" name="titulo" id="id_titulo" />
    </p>
    <p>
        <label for="id_imagem_url">URL da imagem:</label>
        <input type="url" name="imagem_url" id="id_imagem_url" />
    </p>
    <p>
        <label for="id_conteudo">Conteúdo:</label>
        <input type="text" name="conteudo" id="id_conteudo" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

posts/templates/posts/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'posts:delete' post.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar este jogo "{{ post.titulo }} ({{ post.data_criacao|date:"SHORT_DATE_FORMAT" }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

posts/templates/posts/detail.html
{% extends 'base.html' %}

{% block title %}
{{ post.titulo }} ({{ post.data_criacao|date:"SHORT_DATE_FORMAT" }}
{% endblock title %}

{% block content %}
<h2>Detalhes da Fake News {{ post.titulo }} ({{ post.data_criacao|date:"SHORT_DATE_FORMAT" }})</h2>

<section class="dados-de-filme">
    <img src="{{ post.imagem_url }}" alt="Imagem do jogo {{ post.titulo}}">
    <ul>
        <li>Título: {{ post.titulo }}</li>
        <li>Data de criação: {{ post.data_criacao|date:"SHORT_DATE_FORMAT" }} </li>
        <li>Conteúdo: {{ post.conteudo|safe|escape }}</li>
        <li><a href="{% url 'posts:update' post.id %}">Editar jogo</a></li>
        <li><a href="{% url 'posts:delete' post.id %}">Apagar jogo</a></li>
    </ul>
</section>

{% endblock content %}

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os jogos do Blog</h2>
<section>
    <p>Não encontrou seu jogo? <a href="{% url 'posts:create' %}">Adicionar novo jogo</a></p>
</section>
{% if post_list %}
<section class="lista-de-cards">
    {% for post in post_list %}
    <article class="card">
        <a href="{% url 'posts:detail' post.id %}"><img src="{{ post.imagem_url }}"
                alt="Imagem do Post {{ post.titulo}}"></a>
        <p>{{ post.titulo }} ({{ post.data_criacao|date:"SHORT_DATE_FORMAT" }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum jogo.</p>
{% endif %}

{% endblock content %}

posts/templates/posts/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do jogo {{ post.titulo }} ({{ post.data_criacao|date:"SHORT_DATE_FORMAT"}})</h2>
<form method="POST" action="{% url 'posts:update' post.id%}">
    {% csrf_token %}
    <p>
        <label for="id_titulo">Título:</label>
        <input type="text" name="titulo" id="id_titulo" value="{{ post.titulo }}" />
    </p>
    <p>
        <label for=" id_imagem_url">URL da imagem:</label>
        <input type="url" name="imagem_url" id="id_imagem_url" value="{{post.imagem_url}}" />
    </p>
    <p>
        <label for="id_conteudo">Conteúdo:</label>
        <input type="text" name="conteudo" id="id_conteudo" value="{{ post.conteudo }}" />
    </p>
    <button type="submit">Atualizar jogo</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
<p>Criado como requisito de entrega da disciplina PMR3304 - Sistemas de Informação</p>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Game Blog - Os jogos da comunidade</i></h1>
<p>A Página para Comunidade de Jogos da internet</p>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Blog de Jogos
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logo.png' %}"> </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'posts:index' %}">Jogos</a></li>
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>

    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021 - Tiago Cavalcanti Lira de Carvalho - NUSP 12412482</small>
        </p>
    </footer>
</body>

</html>